# Generated by Django 2.1.5 on 2019-11-21 15:42

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate3_id_new', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cate1_id', models.CharField(max_length=200)),
                ('cate1_name', models.CharField(max_length=200)),
                ('cate2_id', models.CharField(max_length=200)),
                ('cate2_name', models.CharField(max_length=200)),
                ('cate3_id', models.CharField(max_length=200)),
                ('cate3_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('cate3_id_new',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_posts', to='taggit.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
