# Generated by Django 2.1.5 on 2019-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191122_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate1_id', models.CharField(max_length=80)),
                ('cate1_name', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
