# Generated by Django 2.1.5 on 2019-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate2_id', models.CharField(max_length=80)),
                ('cate2_name', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate3_id', models.CharField(max_length=80)),
                ('cate3_name', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
